repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: b969e2851312ca2b24bbec879ba4954341d1bd12 # frozen: v0.15.5
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/semgrep/pre-commit
    rev: "300faea09b7bc82adb8280d3b640ba81f813e22a" # frozen: v1.154.0
    hooks:
      - id: semgrep
        entry: semgrep
        # See https://semgrep.dev/explore for the list
        args:
          - --config=p/python
          - --config=p/trailofbits
          - --config=p/dockerfile
          - --config=p/docker
          - --config=p/docker-compose
          - --config=p/github-actions
          - --config=p/trailofbits
          - --config=r/yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
          - --error
          - --skip-unknown-extensions
