sudo: false
language: python

git:
  depth: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

cache:
  pip: true
  directories:
    - node_modules
      - $HOME/.cache/pip
      - $HOME/.cache/pre-commit

env:
  - DJANGO="==1.11.*"
  - DJANGO="==2.1.*"
  - DJANGO="==2.2.*"
  - DJANGO="master"
  - TEST_PYPI="true"

matrix:
  fast_finish: true
  include:
    - dist: xenial
      python: "3.5"
      env:
        - DJANGO="==2.2.*"

    - dist: xenial
      python: "3.6"
      env:
        - DJANGO="==2.2.*"

    - dist: xenial
      python: "3.6"
      env:
        - DJANGO="master"

    - dist: xenial
      python: "3.7"
      env:
        - DJANGO="==2.2.*"

    - dist: xenial
      python: "3.7"
      env:
        - DJANGO="master"

    - dist: xenial
      python: "3.6"
      env:
        - TEST_PRECOMMIT="true"

  exclude:
    - python: "2.7"
      env: DJANGO="==2.1.*"
    - python: "2.7"
      env: DJANGO="==2.2.*"
    - python: "2.7"
      env: DJANGO="master"
    - python: "3.4"
      env: DJANGO="==2.1.*"
    - python: "3.4"
      env: DJANGO="==2.2.*"
    - python: "3.4"
      env: DJANGO="master"
    - python: "3.5"  # We need to use xenial here instead of trusty
      env: DJANGO="==2.2.*"
    - python: "3.5"
      env: DJANGO="master"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y sqlite3

install:
  - >
    if [ -n "$DJANGO" ]; then
      [ "$DJANGO" == master ] \
         && django=https://github.com/django/django/archive/master.tar.gz \
         || django="django${DJANGO}"
    fi
  - pip install tox-travis codecov coverage $django
  - >
    if [ -n "$TEST_PYPI" ]; then
      if [ -n "$TRAVIS_TAG" ]; then
        pip install -r requirements_dev.txt
        pip install pytest-django-queries --pre
      fi
    elif [ -n "$TEST_PRECOMMIT" ]; then
      pip install pre-commit
    else
      ./setup.py develop \
      && pip install -e .[dev]
    fi


script:
  - >
    if [ -n "$TEST_PYPI" ]; then
      if [ -n "$TRAVIS_TAG" ]; then
        pytest
      else
        echo Nothing to do >&2
      fi
    elif [ -n "$TEST_PRECOMMIT" ]; then
      pre-commit run --all-files
    else
      coverage run --source pytest_django_queries -m pytest
    fi

after_success: codecov
