dist: xenial
os: linux
language: python

git:
  depth: false

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

cache:
  pip: true
  directories:
    - node_modules
      - $HOME/.cache/pip
      - $HOME/.cache/pre-commit

env:
  - DJANGO="==1.11.*"
  - DJANGO="==2.0.*"
  - DJANGO="==2.1.*"
  - DJANGO="==2.2.*"
  - DJANGO="==3.0.*"
  - DJANGO="==3.1.*"
  - DJANGO="master"
  - TEST_PYPI="true"

jobs:
  fast_finish: true
  include:
    - python: "3.8"
      env:
        - TEST_PRECOMMIT="true"

    - python: "3.8"
      env:
        - DJANGO="==3.1.*"
        - TEST_PYTEST_XDIST_134="==3.1.*"

  exclude:
    - python: "3.8"
      env: DJANGO="==1.11.*"

    - python: "3.8"
      env: DJANGO="==2.0.*"

    - python: "3.8"
      env: DJANGO="==2.1.*"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y sqlite3

install:
  - |
    if [ -n "$DJANGO" ]; then
      [ "$DJANGO" == master ] \
         && django=https://github.com/django/django/archive/master.tar.gz \
         || django="django${DJANGO}"
    fi
  - pip install -r requirements_test.txt $django
  - |
    if [ -n "$TEST_PYPI" ]; then
      if [ -n "$TRAVIS_TAG" ]; then
        pip install -r requirements_dev.txt
        pip install pytest-django-queries --pre
      fi
    elif [ -n "$TEST_PRECOMMIT" ]; then
      pip install pre-commit
    else
      ./setup.py develop \
      && pip install -e .[dev]
    fi
  - |
    [ -z "$TEST_PYTEST_XDIST_134" ] || pip install pytest-xdist\<2.0


script:
  - |
    if [ -n "$TEST_PYPI" ]; then
      if [ -n "$TRAVIS_TAG" ]; then
        pytest
      else
        echo Nothing to do >&2
      fi
    elif [ -n "$TEST_PRECOMMIT" ]; then
      pre-commit run --all-files
    else
      coverage run --source pytest_django_queries -m pytest
    fi

after_success: codecov
