# Generated by Django 6.0.2 on 2026-02-28 14:24

import django.db.models.deletion
from django.db import migrations, models


def populate_models(apps, schema_editor):
    Book = apps.get_model("books", "Book")
    Author = apps.get_model("books", "Author")

    Author.objects.bulk_create(Author(id=i, name=f"Author {i}") for i in range(1, 11))

    Book.objects.bulk_create(
        Book(id=i, name=f"Book {i}", author_id=i) for i in range(1, 11)
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="books.author"
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_models, migrations.RunPython.noop),
    ]
